ARCHIVE_NAME = mbedtls_ecp_compression
ARCHIVE_INCLUDES =

$(ARCHIVE_NAME)_SRC_DIR = $(SUBMODULE_DIR)/mbedtls_ecp_compression
$(ARCHIVE_NAME)_SRC = $($(ARCHIVE_NAME)_SRC_DIR)/ecc_point_compression.c
$(ARCHIVE_NAME)_INCLUDE = -I $($(ARCHIVE_NAME)_SRC_DIR)

include Makefile.archive
